version: "3.4"

services:
  php:
    build:
      context: .
      target: app
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.ini:/usr/local/etc/php/conf.d/app.ini:ro
      - php_socket:/var/run/php
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

volumes:
  php_socket:
